chore: cleanup setting tooltips that are too long
pajlads/DinkPlugin pull request #151
Opened 2023-01-31 03:45 UTC by Felanbird

To combat extremely long setting tool-tips, I've gone ahead and taken the long sentences and converted them into multi-line lists.

before:
![image](https://user-images.githubusercontent.com/41973452/215656981-b4fb925b-6f8e-42e1-a693-ab475dbe1b4b.png)

after:
![image](https://user-images.githubusercontent.com/41973452/215657063-0ba4d169-fd73-456d-9dd5-9e930ef808a3.png)

Can wait until Barb Assault PR is merged, I have no issue applying these same changes to the changes from that PR

2023-01-31 16:45 UTC, equirs commented
> Can wait until Barb Assault PR is merged

I can also rebase and change any tooltips I've added. That PR is waiting for the next stable RL release anyway, so don't want to slow you down

2023-02-01 21:03 UTC, iProdigy approved these changes

2023-02-01 21:10 UTC, pajlada requested changes

2023-02-01 21:10 UTC, pajlada commented on CHANGELOG.md
> +- Minor: Cleanup setting tooltips that stretched too wide, making them difficult to read. (#151)
I think this is actually correct
```suggestion
- Minor: Clean up setting tooltips that stretched too wide, making them difficult to read. (#151)
```

2023-02-01 21:10 UTC, zneix approved these changes

2023-02-01 21:12 UTC, pajlada approved these changes

2023-02-01 21:18 UTC, merged