perf: avoid multiple initLevels calls in a single tick
pajlads/DinkPlugin pull request #251
Opened 2023-05-30 19:48 UTC by iProdigy

Follow-up from #250

2023-05-31 07:09 UTC, pajlada approved these changes
Code looks good to me, haven't tested

2023-06-11 07:30 UTC, pajlada requested changes
Code looks good, just changelog nitpick

2023-06-11 07:30 UTC, pajlada commented on CHANGELOG.md
>  - Bugfix: Avoid combat level notifications that don't conform to the configured interval. (#250)
The changelog entry is duplicated

2023-06-11 15:43 UTC, pajlada approved these changes

2023-06-12 17:38 UTC, Felanbird approved these changes
I attempted to review this PR but then after I finished realized I was still on the current master from trying to replicate the bug(s) that this PR fixes.

So we're just gonna say this works and hope for the best 🤞

2023-06-13 01:00 UTC, merged