feat: include kill count for npc loot notifications
pajlads/DinkPlugin pull request #299
Opened 2023-08-24 17:22 UTC by iProdigy

Closes #296

![image](https://github.com/pajlads/DinkPlugin/assets/8106344/d01a30c0-20fd-4214-bd74-94074c68347c)

This PR relies upon the base loot tracker plugin observing all kills. In a future PR, we will use boss chat messages to override base loot tracker for more account kc stats

2023-08-24 19:54 UTC, Felanbird commented
I think the main issue is coming from the KC value not correctly getting updated, or we're not reading it correctly.
When killing enemies in quick succession, the KC is not updated, but after x amount of time the KC does update (checked quicker-succession and that didn't work, likely real-time). 
First kill and update kill being 1-off always tho.

<br/><br/>

Red: KC as reported by dink
Lime Green: Correct KC
Cyan: Timestamp

<details>
<summary>Rune dragons:</summary>

![image](https://github.com/pajlads/DinkPlugin/assets/41973452/a0d2ba59-830a-49b9-bba5-7ef6d3f7c894)


I disabled JSON after the 4 kills since I figured it wasn't going to change, which is why some timestamps have seconds
```
   "extra":{
      "items":[
         {
            "id":2363,
            "quantity":1,
            "priceEach":12280,
            "name":"Runite bar"
         },
         {
            "id":19580,
            "quantity":26,
            "priceEach":515,
            "name":"Rune javelin heads"
         }
      ],
      "source":"Rune dragon",
      "category":"NPC",
      "killCount":571
   },
```
```
   "extra":{
      "items":[
         {
            "id":2363,
            "quantity":1,
            "priceEach":12280,
            "name":"Runite bar"
         },
         {
            "id":19582,
            "quantity":31,
            "priceEach":889,
            "name":"Dragon javelin heads"
         }
      ],
      "source":"Rune dragon",
      "category":"NPC",
      "killCount":571
   },
```
```
   "extra":{
      "items":[
         {
            "id":2363,
            "quantity":1,
            "priceEach":12280,
            "name":"Runite bar"
         },
         {
            "id":562,
            "quantity":88,
            "priceEach":45,
            "name":"Chaos rune"
         }
      ],
      "source":"Rune dragon",
      "category":"NPC",
      "killCount":571
   },
```
```
   "extra":{
      "items":[
         {
            "id":2363,
            "quantity":1,
            "priceEach":12280,
            "name":"Runite bar"
         },
         {
            "id":1303,
            "quantity":1,
            "priceEach":18408,
            "name":"Rune longsword"
         }
      ],
      "source":"Rune dragon",
      "category":"NPC",
      "killCount":571
   },
```
</details>

<details>
<summary>H.A.M Guards</summary>

![image](https://github.com/pajlads/DinkPlugin/assets/41973452/22804a2b-a4b4-4efa-8c46-cd40d501d810)

</details>

2023-08-26 11:10 UTC, pajlada requested changes
Looks like a very reasonable implementation :+1: Small nitpicks/comments

2023-08-26 11:10 UTC, pajlada commented on src/main/java/dinkplugin/util/SerializedLoot.java
> +public class SerializedLoot {
Comment specifying where this comes from, if it's a struct from Runelite. maybe link to the file with a github link?

2023-08-26 19:36 UTC, pajlada approved these changes
Code looks good to me, and I agree with the multi-step approach of this feature.
Basic Loot Tracker-based KC first, more advanced KC-tracking later (bosses etc)

2023-08-26 22:26 UTC, Felanbird approved these changes
Seems to now work as I would expect it to 👍

2023-08-26 23:02 UTC, merged