feat: add allowlist filter mode for rsn advanced config
pajlads/DinkPlugin pull request #306
Opened 2023-09-04 00:36 UTC by iProdigy

Closes #305

![image](https://github.com/pajlads/DinkPlugin/assets/8106344/deeb3ce8-f5cf-42b0-a174-a11f6a00a7d0)

2023-09-05 03:49 UTC, Newbcake commented
Hey just wanna show my thanks here, seriously appreciate it.

2023-09-09 11:54 UTC, pajlada approved these changes
Everything looks good to me, with sane defaults & the phrasing we use I think this is good to merge :+1: 
A language-check on the README/changelog and it should be good to go

2023-09-09 11:54 UTC, pajlada commented on src/main/java/dinkplugin/DinkPluginConfig.java
> +        name = "Filtered RSNs",
Name choice is good

2023-09-09 19:22 UTC, iProdigy commented
A remaining complication: on config import, the current settings and the imported settings may have a different name filter mode. Seems weird to combine the text boxes when the modes differ?

2023-09-09 19:23 UTC, iProdigy commented on src/main/java/dinkplugin/DinkPluginConfig.java
> +        description = "Allow Mode: Only allow notifications for RSNs on the list above.<br/>" +
```suggestion
        description = "Allow Mode: Only allow notifications for RSNs on the list above (discouraged).<br/>" +
```

Do we want to add a warning here?

2023-09-09 19:24 UTC, iProdigy commented
@Felanbird could you also review the wording of settings/readme please

2023-09-09 19:38 UTC, Felanbird requested changes

2023-09-09 19:38 UTC, Felanbird commented on src/main/java/dinkplugin/SettingsManager.java
> +     * Check whether a username adheres to the configured RSN filter list.
```suggestion
     * Check whether a username complies with the configured RSN filter list.
```

I think adhere basically never fits in coding, also comply was already used in the readme

2023-09-09 19:38 UTC, Felanbird commented on CHANGELOG.md
> +- Minor: Add allowlist mode for RSN-based notification filter under the Advanced category. Use this setting with caution. (#306)
```suggestion
- Minor: Add allowlist mode for Filtered RSNs under the Advanced category. Use this setting with caution. (#306)
```

2023-09-09 19:41 UTC, Felanbird approved these changes

2023-09-09 19:45 UTC, merged