feat: add leagues notifier for areas, relics, and tasks
pajlads/DinkPlugin pull request #366
Opened 2023-11-16 05:29 UTC by iProdigy

Closes #356

Notifies on:
* Area unlocked
* Relic unlocked
* Task completed

![image](https://github.com/pajlads/DinkPlugin/assets/8106344/f3c95fb1-f1f9-42f2-bdcd-4e8283220621)

2023-11-16 09:25 UTC, Felanbird commented
tasks work
task filtering works

2023-11-16 10:17 UTC, iProdigy commented on src/main/java/dinkplugin/notifiers/LeaguesNotifier.java
> +        TIER_BY_RELIC = Map.ofEntries(
In a future PR, can switch hardcoded relic names to dynamic lookup from structs/enums

2023-11-17 03:46 UTC, Felanbird approved these changes
I tested everything except region unlock, I believe it all works

2023-11-17 04:19 UTC, iProdigy commented
I'll try to get a region unlock tonight before falling asleep to test that branch

2023-11-17 10:20 UTC, iProdigy commented
area notif works

![image](https://github.com/pajlads/DinkPlugin/assets/8106344/ca7a10c7-72f2-4b91-81e9-99120304fd50)

2023-11-17 11:39 UTC, pajlada requested changes
Code looks good to me, two nitpicks is all I could find

2023-11-17 11:39 UTC, pajlada commented on src/main/java/dinkplugin/notifiers/data/LeaguesAreaNotificationData.java
> +    Integer tasksUntilNextArea;
Mark as nullable

2023-11-17 11:39 UTC, pajlada commented on src/main/java/dinkplugin/notifiers/LeaguesNotifier.java
> +            }
Could the tier-logic be scoped so the assignment doesn't happen inside the if-statement?
e.g.
```java
if (matcher.find()) {
  tier = ...;
  if (tier != null & tier.ordinal...) {
    notifyTaskCompletion
  }
}
```

2023-11-17 19:06 UTC, pajlada approved these changes

2023-11-17 19:07 UTC, merged