feat(death): allow customization of ignored regions
pajlads/DinkPlugin pull request #415
Opened 2024-01-29 23:16 UTC by iProdigy

Closes #414

2024-01-30 00:58 UTC, Felanbird requested changes
nits

2024-01-30 00:58 UTC, Felanbird commented on src/main/java/dinkplugin/DinkPluginConfig.java
> +        return "8781, 12336, 13462, 13463";
I feel like we can use ones that are just in the middle of nowhere? e.g. in the ocean, most of the time you can't even access those so you should be unable to die in them.

```suggestion
        return "4904, 5930, 6953, 7723";
```

<details>
<summary>locations</summary>

![image](https://github.com/pajlads/DinkPlugin/assets/41973452/9006d3cc-3858-4177-b0cb-6c688a60f5c9)

</details>

2024-01-30 00:58 UTC, Felanbird commented on src/main/java/dinkplugin/DinkPluginConfig.java
> +            "Use the '::DinkRegion' chat command or an online map to obtain the region IDs.<br/>" +
```suggestion
            "Use the '::dinkregion' chat command or an online map to obtain the region IDs.<br/>" +
```
command is case-insensitive and our export command readme mentions are lowercase

2024-01-30 03:08 UTC, iProdigy commented on src/main/java/dinkplugin/DinkPluginConfig.java
> +        return "4904, 5930, 6953, 7723";
perhaps we use some obviously fake IDs so its clearer that users can delete them

```suggestion
        return "123, 456, 789";
```

2024-01-30 03:20 UTC, Felanbird approved these changes
I tested the region where the Jail Guard is outside of Draynor `12338` and it worked as expected

2024-01-30 08:36 UTC, pajlada reviewed
I would like this feature, together with the `::DinkRegion` command, mentioned in the readme file, but that's probably best to do once #416 has been merged in. The text should mention deathpiling & UIM so it can be CTRL+F'd easily

2024-01-31 08:24 UTC, pajlada approved these changes

2024-01-31 09:05 UTC, merged